CREATE TABLE product
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku        VARCHAR(64)              NOT NULL,
    name       VARCHAR(200)             NOT NULL,
    unit       VARCHAR(16)              NOT NULL,
    min_stock  INTEGER                  NOT NULL CHECK (min_stock >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_product_sku UNIQUE (sku)
);

CREATE TABLE storage_location
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32)  NOT NULL,
    name VARCHAR(200) NOT NULL,
    CONSTRAINT uk_storage_location_code UNIQUE (code)
);

-- Current quantity of one product at one location.
-- The CHECK constraint is the last line of defence against negative stock.
CREATE TABLE stock_level
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT  NOT NULL REFERENCES product (id),
    location_id BIGINT  NOT NULL REFERENCES storage_location (id),
    quantity    INTEGER NOT NULL CHECK (quantity >= 0),
    version     BIGINT  NOT NULL,
    CONSTRAINT uk_stock_level_product_location UNIQUE (product_id, location_id)
);

-- Append-only journal of every goods movement (audit trail).
CREATE TABLE stock_movement
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             VARCHAR(16)              NOT NULL,
    product_id       BIGINT                   NOT NULL REFERENCES product (id),
    from_location_id BIGINT REFERENCES storage_location (id),
    to_location_id   BIGINT REFERENCES storage_location (id),
    quantity         INTEGER                  NOT NULL CHECK (quantity > 0),
    reference        VARCHAR(100),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_stock_level_location ON stock_level (location_id);
CREATE INDEX idx_stock_movement_product_created ON stock_movement (product_id, created_at DESC);
